name: Release Deploy

on:
  release:
    types: [ created ]

defaults:
  run:
    working-directory: ./src/

jobs:
  copy-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4.1.1

      - name: Upload to FTP server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          local-dir: ./src/
          server-dir: public_html/2023-2024/
